export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
}
export enum TaskStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
}
export enum AuditActionType {
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',
  STATUS_UPDATED = 'STATUS_UPDATED',
  ASSIGNMENT_UPDATED = 'ASSIGNMENT_UPDATED',
}
